from exceptions import get_int

class TestGetInt:
    pass
